### PR TITLE
Author does not have a twitter profile

### PR DESCRIPTION
**Pull request by gbraad**
Anders does not use Twitter, so the link to the profile is erroneous (empty; links to the homepage)

### CODE REVIEW

**Comment by gbraad** [comment]
@afbjorklund right?

**Comment by afbjorklund** [comment]
@gbraad : you are right, guess the template just assumed everyone uses twitter...

**Comment by afbjorklund** [comment]
Actually I did have https://twitter.com/afbjorklund - just never saw a use for it.

**Comment by rhatdan** [comment]
LGTM

**Pull request merged**
