### PR TITLE
Remove nix documentation since it is no longer supported

### LINKED ISSUE #515: Nix static build no longer supported
Recently the installation of Podman via Nix has been discontinued it seems:

https://github.com/containers/podman/commit/346beec35a11393e9c59278d47b18de337c2b06f

The installation instructions need to be amended. At first I wanted to make the changes my self, but I am not sure about the implications for static builds in general.

https://github.com/aebd37cab9ff742b/podman.io/blob/e0d8c4306de702b10781cc987ba2f86fc1481c53/getting-started/installation.md?plain=1#L395-L413

### PR DESCRIPTION
**Pull request by rhatdan**
Fixes: https://github.com/containers/podman.io/issues/515

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@TomSweeneyRedHat PTAL

**Review by Luap99 — COMMENTED** [review]
LGTM

**Review by TomSweeneyRedHat — COMMENTED** [review]
LGTM
would like to still have it, but appropriate to pull it at this point

**Comment by aebd37cab9ff742b** [comment]
Your changes break the document's hierarchy.

The section "Ansible" used to be a subsection of "Static build".

Now "Ansible" is a subsection of "Vendoring - Dependency Management".

**Comment by rhatdan** [comment]
Please open a PR to fix this.

**Pull request merged**
