### PR TITLE
add a Gemfile for local development

### PR DESCRIPTION
**Pull request by robbyoconnor**
Add a Gemfile so that people can test their changes locally.

### CODE REVIEW

**Comment by this-is-rafa** [comment]
I was confused by this also (and wasted about 35mins) but it doesn't actually need a gemfile. The instructions on how to edit the website just aren't clear.

What you need to do is clone the repo and then install the GitHub pages gem (`gem install github-pages`) if you don't already have it. You don't need to install Jekyll separately as it's included with Github Pages. From there you can build the site running `jekyll build` or serve the site locally with `jekyll serve`.

Instead of adding a gemfile it might be better to just make that clear in the README.

**Comment by robbyoconnor** [comment]
@this-is-rafa -- it's not your fault at all -- this makes it clearer now =)

**Comment by robbyoconnor** [comment]
I'm not just here to complain -- I help when I can :)

**Comment by TomSweeneyRedHat** [comment]
@this-is-rafa :+1:  It's been a bit since I've last built the site locally and wanted to do so for the review.  I too was struggling a bit as I've a new development machine and bad notes since the last time I've done this.  If you don't beat me to the punch, I'll add a note on how to run and serve this with jekyll to the README.md

**Comment by robbyoconnor** [comment]
@TomSweeneyRedHat Added the docs so the next person doesn't have to struggle :)

**Comment by robbyoconnor** [comment]
Open Source is all about helping where you can in my eyes.

**Comment by TomSweeneyRedHat** [comment]
@robbyoconnor I appreciate the PR and your comments on the PR's, but we don't need the Gemfile from what I can see and would rather not add it unless you can educate me otherwise.  FWIW, here's my rough cheat sheet on how to  run the server locally, assuming you're running your sandbox on the vm:

```
# Configuration
dnf -y install ruby
dnf -y install ruby-devel
dnf -y install g++
gem install jekyll bundler
gem install github-pages


On VM:
# firewall-cmd --permanent --add-port=4000/tcp
success
# firewall-cmd --reload
success

cd into podman.io in your development sandbox.

# New build
bundle exec jekyll build
bundle exec jekyll serve --host 192.###.###.###   - IP Address of VM

# In browser on the machine running the VM:
http://{IP.address}:4000

```

I was going to run through that one more time on a fresh VM to make sure I had it right before posting to the README.md fwiw.

**Comment by robbyoconnor** [comment]
@TomSweeneyRedHat -- It's two files...but ultimately your pregative on this. I'm trying to just help out when I can. 

Hope you're well.

**Comment by TomSweeneyRedHat** [comment]
@robbyoconnor I've decided to leave the Gemfile and the Gemfile.lock out of the equation and have stolen your instructions and added them in #376.  
Thanks a bunch for your help with this!
FWIW, I am indeed well, and hope you and your family are too.

**Pull request closed without merging**
