### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by jjasghar**
Fixing some formatting on the main page.

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM thanks @jjasghar 
@rhatdan PTAL and merge if it LGTY

**Comment by Luap99** [comment]
This is how it would look like:
image
If you prefer this style I'm fine with it but it should be changed in the `whatis.md` as well

**Comment by TomSweeneyRedHat** [comment]
@Luap99 thanks for the 411, I thought it was just my fat fingers that had accidentally left behind the backslash.  @rhatdan, I'll let you pick, I like both styles, but think I prefer the '\\\'' variety

**Comment by rhatdan** [comment]
Is there a way to get this bolded, I think that is the goal of the "`" marks.  I would prefer not to have the marks on the final screen but have it bolded, or highlighted.

**Comment by Luap99** [comment]
Bold would be this syntax: `**alias docker=podman**`

**Comment by Luap99** [comment]
image

**Comment by rhatdan** [comment]
That LGTM

**Comment by jjasghar** [comment]
Closed per your suggestions and created this: https://github.com/containers/podman.io/pull/269

**Pull request closed without merging**
