### PR TITLE
Fix Ubuntu & Add Debian 10 (buster) installation instructions

### PR DESCRIPTION
**Pull request by rahilarious**

### CODE REVIEW

**Comment by rhatdan** [comment]
Thanks @rahilarious 
@lsm5 @vrothberg PTAL

**Review by lsm5 — COMMENTED** [review]
Nope from me. We're not maintaining the kubic stable repos anymore, so we shouldn't mention it on the official docs.

**Comment by lsm5** [comment]
@rahilarious if you can update the docs for those distros without any mention of `kubic:libcontainers:stable` (IOW installing some other way), I'd be happy to take another look. HTH.

**Comment by rahilarious** [comment]
@lsm5 I mean I can change the `.list` file name to unstable but can't change the repo link. That was only "simple" way I found to install podman on Ubuntu 18.04 and Debian 10.

**Comment by vrothberg** [comment]
Thanks for opening the PR, @rahilarious !

I agree with @lsm5.  Now as Podman is in the official repositories, we want to encourage users to update to more recent version of Debian and Ubuntu.  The Kubic repositories are not meant for production use.

**Comment by rahilarious** [comment]
> Thanks for opening the PR, @rahilarious !
> 
> I agree with @lsm5. Now as Podman is in the official repositories, we want to encourage users to update to more recent version of Debian and Ubuntu. The Kubic repositories are not meant for production use.

Totally agree with you. But what about distros (debian 10 ubuntu 18.04) where packages aren't available in official repos? They both haven't reached EOL yet

**Comment by vrothberg** [comment]
> Totally agree with you. But what about distros (debian 10 ubuntu 18.04) where packages aren't available in official repos? They both haven't reached EOL yet

I recommend upgrading to newer distribution releases.  I understand that this may not work for all users but it's practically impossible to maintain production-grade packages for all (versions of all) distributions. Ubuntu 18.04 is 5 years old and was released before Podman 1.0.

**Comment by lsm5** [comment]
> > Thanks for opening the PR, @rahilarious !
> > I agree with @lsm5. Now as Podman is in the official repositories, we want to encourage users to update to more recent version of Debian and Ubuntu. The Kubic repositories are not meant for production use.
> 
> Totally agree with you. But what about distros (debian 10 ubuntu 18.04) where packages aren't available in official repos? They both haven't reached EOL yet

The current packages in the kubic-stable repo are probably *not* immune to some recent CVEs. So, we really shouldn't be  mentioning that repo. The only suitable options for those distros right now would be to either build from source, or install from homebrew (if they support those distro versions).

**Pull request closed without merging**
