### PR TITLE
Placeholder for why Podman exists

### PR DESCRIPTION
**Pull request by stappersg**

### CODE REVIEW

**Comment by stappersg** [comment]
Please explain why _Podman_ exists.

**Comment by TomSweeneyRedHat** [comment]
@rhatdan want to take a stab at this?

**Comment by rhatdan** [comment]
Sure. Do we have any existing content for this?

**Comment by TomSweeneyRedHat** [comment]
@rhatdan only the template that @stappersg put together in this PR.  I think it's a good landing spot for it.

**Comment by rhatdan** [comment]
@TomSweeneyRedHat Want to move forward on this?

**Comment by TomSweeneyRedHat** [comment]
@rhatdan yes, and I thought you were going to get your fingers flowing and throw down a few points of interest in a pr!

**Comment by rhatdan** [comment]
I will be in the office tomorrow and Friday. Let's meet and see if we can hash this one out.

**Comment by rhatdan** [comment]
After reading the description, I think what we have now is fine.  If someone needs to enhance it please open a PR.

**Pull request closed without merging**
