### PR TITLE
June 2021 pointers to posts

### PR DESCRIPTION
**Pull request by TomSweeneyRedHat**
Add a blog post with pointers to a number of posts that have popped up in different sites the past
few months.

Also add info about the Cable meetings.

Signed-off-by: TomSweeneyRedHat <tsweeney@redhat.com>

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
@rhatdan PTAL and merge if it LGTY

**Comment by TomSweeneyRedHat** [comment]
PING @rhadan merge me!

**Comment by TomSweeneyRedHat** [comment]
@rhatdan even!

**Comment by TomSweeneyRedHat** [comment]
And sorry for the interupt @rhadan, I misplaced a 't' in my earlier comment.

**Comment by rhatdan** [comment]
LGTM

**Comment by Rhadan** [comment]
I noticed. XD

Am Mi., 16. Juni 2021 um 22:31 Uhr schrieb Tom Sweeney <
***@***.***>:

**Pull request merged**
