### PR TITLE
New blog post: debbuild packaging

### PR DESCRIPTION
**Pull request by lsm5**
Pointer to full post on opensource.com
Ref: https://opensource.com/article/22/9/podman-packages-linux

Signed-off-by: Lokesh Mandvekar <lsm5@fedoraproject.org>

@TomSweeneyRedHat @rhatdan PTAL

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Review by TomSweeneyRedHat — COMMENTED** [review]
This is good for the front page, but you ought to create an almost mirror image of this file and name it something like _posts/2022-10-03-debbuild.md and then change the categories from "[new]" to "[blogs]".  That way it will show up on both the new page, and long term, under the blogs link of the home page.

Otherwise, LGTM

**Comment by lsm5** [comment]
oh ok, let me do that and bump this PR. don't merge until then, thanks!

**Comment by lsm5** [comment]
@TomSweeneyRedHat done, thanks

**Review by TomSweeneyRedHat — COMMENTED** [review]
LGTM

**Pull request merged**
