### PR TITLE
Add Podman 2.1 Release Announcement

### PR DESCRIPTION
**Pull request by TomSweeneyRedHat**
Signed-off-by: TomSweeneyRedHat <tsweeney@redhat.com>

As the title says

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
@mheon @baude @rhatdan PTAL

**Comment by mheon** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
@rhatdan PTAL and merge if it LGTY

**Comment by mheon** [comment]
@rhatdan PTAL

**Comment by rhatdan** [comment]
LGTM

**Pull request merged**
