### PR TITLE
Add network upgrade notes for CNI

### PR DESCRIPTION
**Pull request by computator**
This addresses containers/podman#17048

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM
@TomSweeneyRedHat PTAL

**Comment by lsm5** [comment]
@computator LGTM, but before we merge, could you please add your signoff on the commit ?

**Comment by TomSweeneyRedHat** [comment]
LGTM, once signed (git commit --amend -s, git fetch --all, git rebase upstream/main, git push ....)

**Comment by computator** [comment]
Updated!

**Pull request merged**
