### PR TITLE
Config: Fix bad podman.io url

### LINKED ISSUE #93: podman.io/feed.xml has bad podman.io urls
Hi!

I'm following podman development with my feedreader and the URL's pointing to podman.io look like this most of the time:
```html
<link href="https:/podman.io/feed.xml" rel="self" type="application/atom+xml" />
```
Note the *single* `/` there after `https:`!

This makes the links from my feed reader not working correctly (I end up at `https://podman.io/podman.io/new/2019/04/16/new.html`) 😢

### PR DESCRIPTION
**Pull request by mattiasb**
- Fix bad `podman.io` url
- Prefix YAML with `---` to silence [yamllint](http://www.yamllint.com/).

Fixes: #93

### CODE REVIEW

**Comment by mattiasb** [comment]
This PR is untested, I'm simply making the assumption that these small changes won't break anything. :)

**Review by TomSweeneyRedHat — COMMENTED** [review]
LGTM
@rhatdan PTAL

**Comment by TomSweeneyRedHat** [comment]
Thanks for the PR @mattiasb !

**Comment by rhatdan** [comment]
LGTM

**Pull request merged**
