### PR TITLE
Add article about checkpoint/restore

### PR DESCRIPTION
**Pull request by adrianreber**
See: https://github.com/containers/libpod/pull/469

Signed-off-by: Adrian Reber <areber@redhat.com>

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM, Very nice article @adrianreber thanks for posting it.  @rhatdan do you want to take a looksee before I post?

**Comment by rhatdan** [comment]
LGTM

**Comment by rhatdan** [comment]
@TomSweeneyRedHat lets publish tomorrow, and ask people to social media this.

**Comment by TomSweeneyRedHat** [comment]
@rhatdan ack, I'll create a little new page for this and publish this Wednesday morn. Thanks again @adrianreber !

**Comment by TomSweeneyRedHat** [comment]
@adrianreber hold off advertising this atm, I'm going to change the name of the file slightly.

**Comment by TomSweeneyRedHat** [comment]
@adrianreber Just posted, the blog is at:  https://podman.io/blogs/2018/10/10/checkpoint-restore.html feel free to social media this as you wish, we'll be doing the same.  Thanks again for the article!

**Pull request merged**
