### PR TITLE
update install instructions for Debian and Ubuntu

### PR DESCRIPTION
**Pull request by lsm5**
Signed-off-by: Lokesh Mandvekar <lsm5@fedoraproject.org>

@TomSweeneyRedHat @rhatdan @mheon @baude @vrothberg

### CODE REVIEW

**Comment by lsm5** [comment]
skipped raspbian until https://github.com/containers/libpod/issues/4903 is fixed.

**Comment by lsm5** [comment]
btw, I notice buildah.io's install link points to the buildah github repo itself, while podman.io has this separate page. Maybe just me, but it'd be great to have a consistent look-and-feel.

**Comment by lsm5** [comment]
raspbian build succeeded just now, I'll update this PR..

**Comment by TomSweeneyRedHat** [comment]
@lsm5 it's not just you.  @jberkus was able to spend some time making Podman.io more user-friendly as it generally has more traffic than Buildah.io.  I've not done the same in Buildah.io partially because I like having the install instructions in one place.  But perhaps the longer term answer is to just have the install instructions only on the *.io site and add links in the respective GitHub repo's for both.

**Comment by TomSweeneyRedHat** [comment]
The current verbiage LGTM, will merge in after you update the raspbian stuff too.  Thanks!

**Comment by lsm5** [comment]
@TomSweeneyRedHat ready to go..

**Review by TomSweeneyRedHat — COMMENTED** [review]
LGTM

**Comment by TomSweeneyRedHat** [comment]
and forgot, thanks @lsm5 !

**Pull request merged**
