### PR TITLE
Add the first community mtg notes

### PR DESCRIPTION
**Pull request by TomSweeneyRedHat**
Signed-off-by: TomSweeneyRedHat <tsweeney@redhat.com>

Menu start for the community meetings notes and the first set of notes from the 10/6/2020 meeting.

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
@vrothberg @rhatdan PTAL

**Review by vrothberg — COMMENTED** [review]
LGTM

**Comment by rhatdan** [comment]
LGTM

**Comment by rhatdan** [comment]
@TomSweeneyRedHat We need to update podman.io community patch to talk about the monthly meeting.

**Comment by TomSweeneyRedHat** [comment]
@rhatdan Yep!  I need to add a section fo the community meeting on the community page and include a link to the notes from there along with the next meeting's agenda.  I wanted to get this one through first to see if my thinking on the notes pages worked out.

**Pull request merged**
