### PR TITLE
Create 2021-06-16-install-podman-on-ubuntu.md

### PR DESCRIPTION
**Pull request by hitjethva**
Add a Podman installation link

### CODE REVIEW

**Comment by hitjethva** [comment]
Hi @TomSweeneyRedHat

I have added your suggested file. Please check it.

**Comment by TomSweeneyRedHat** [comment]
LGTM
@hitjethva I thought you'd just add this to your other PR, but this works too.  I'll merge both.  Thanks again!

**Comment by hitjethva** [comment]
Hi @TomSweeneyRedHat 

When you merge the pull request?

**Comment by hitjethva** [comment]
Hi @TomSweeneyRedHat

Any update on [this](https://github.com/containers/podman.io/pull/421/commits/5cb520f81c3f2e7b8b3a82171783fe71b40b1d84)

**Comment by TomSweeneyRedHat** [comment]
@hitjethva sorry for the delay.  I could have sworn I'd merged this and then I didn't see the emails from GitHub until just now. Thanks @rhatdan for covering for me!

**Pull request merged**
