### PR TITLE
Add link to archlinux podman page

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
Fixes: https://github.com/containers/podman/issues/15611

**Comment by rhatdan** [comment]
@TomSweeneyRedHat @vrothberg @mheon PTAL

**Review by vrothberg — APPROVED** [review]
LGTM

**Review by TomSweeneyRedHat — COMMENTED** [review]
LGTM

**Pull request merged**
