### PR TITLE
Update Mac and Windows Install Instructions

### PR DESCRIPTION
**Pull request by n1hility**
Updates the Mac and Windows instructions and points to the new Windows guide.

Signed-off-by: Jason T. Greene <jason.greene@redhat.com>

### CODE REVIEW

**Comment by n1hility** [comment]
PTAL @TomSweeneyRedHat

**Comment by rhatdan** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
Sorry @n1hility looks like a rebase is needed.  I'll try to be a bit more prompt next time, but Brent's recent PR might have negated the need for this.

**Comment by n1hility** [comment]
@TomSweeneyRedHat @baude rebased. It's up to you guys if you want/like the other changes, or prefer as is. The rest are just apply the overall concept to both and breaking apart the differences.

**Comment by TomSweeneyRedHat** [comment]
LGTM
but want a head nod from @baude 
@n1hility TYVM!

**Comment by n1hility** [comment]
@TomSweeneyRedHat you’re welcome. BTW I never really expect anyone to pick up PRs on a Sunday :)

**Pull request merged**
