### PR TITLE
Create new 2021-06-16-new.md file.

### PR DESCRIPTION
**Pull request by hitjethva**
Step by step guide to install Podman on Ubuntu 20.04 with some basic commands.

### CODE REVIEW

**Comment by hitjethva** [comment]
Hi @lsm5 
I have added step by step guide to install Podman on Ubuntu 20.04 with some basic commands. Please check it and merge pull requests.

**Comment by lsm5** [comment]
@hitjethva thanks, I'll defer to @rhatdan and @TomSweeneyRedHat on addition of posts. LGTM from me fwiw.

**Review by TomSweeneyRedHat — COMMENTED** [review]
The post looks fine, thanks for the PR.  I would ask that you create a second file too that will be more permanent.  The New posts we remove after some time (we're actually behind in doing so).  Could you make a second md file, perhaps named:  _posts/2021-06-16-install-podman-on-ubuntu.md with content like:

```
---
title: How to Install and Use Podman on Ubuntu 20.04
layout: default
categories: [blogs]
tags: containers, podman, networking, pod, api, kubernetes, kube, v2, hpc, windows, mac
---
![podman logo](https://podman.io/images/podman.svg)

Hitesh Jethva posted a blog post on the [Atlantic.Net](https://www.atlantic.net/) site talking about [How to Install and Use Podman on Ubuntu 20.04](https://www.atlantic.net/dedicated-server-hosting/how-to-install-and-use-podman-on-ubuntu-20-04/).  In the post Hitesh walks through all the steps necessary from 'A' to 'Z' to get Podman up and running on Ubuntu 20.04 and how to do some initial Podman commands. 

```

**Comment by TomSweeneyRedHat** [comment]
Requested additional page supplied in #421

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Pull request merged**
