### PR TITLE
recommend default centos build for prod environments

### PR DESCRIPTION
**Pull request by lsm5**
Signed-off-by: Lokesh Mandvekar <lsm5@fedoraproject.org>

@mheon @TomSweeneyRedHat @rhatdan 
RE: https://github.com/containers/libpod/issues/5893

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM, but would like another head nod or two before merging.

**Comment by rhatdan** [comment]
LGTM

**Comment by lsm5** [comment]
Thanks all, btw, do we need to add this warning for other ubuntu and debian as well? Those do not have podman in their base repos AFAIK, so this is the only way to get podman there.

**Comment by mheon** [comment]
I don't think we have to until Debian puts Podman in stable, which could be quite some time.

**Comment by bryanpedini** [comment]
> I don't think we have to until Debian puts Podman in stable, which could be quite some time.

It would be nice to have an official stable tho, I just installed podman on my Debian Buster desktop environment and from what I can read on the web I was lucky on the particular version I've installed **most** of the things work as expected, but surely there's room for what I haven't tried yet to fail miserably...
(but that's a discussion for another topic)

**Comment by lsm5** [comment]
> It would be nice to have an official stable tho, I just installed podman on my Debian Buster desktop environment and from what I can read on the web I was lucky on the particular version I've installed **most** of the things work as expected, but surely there's room for what I haven't tried yet to fail miserably...
> (but that's a discussion for another topic)

Official debian packaging work is happening outside of this team. See: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=930440

**Comment by bryanpedini** [comment]
Thanks @lsm5!

**Pull request merged**
