### PR TITLE
Troubleshooting guide post

### PR DESCRIPTION
**Pull request by TomSweeneyRedHat**
Add a short post about Podman's troubleshooting guide.

Google doc will be up for editing too.

Signed-off-by: TomSweeneyRedHat <tsweeney@redhat.com>

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
@mheon PTAL

**Comment by rhatdan** [comment]
LGTM

**Comment by mheon** [comment]
Only comment: Maybe we should add a sentence somewhere suggesting that people should add to the troubleshooting document if they encounter a common pitfall (something in an issue with lots of comments or similar) not on it?

**Comment by TomSweeneyRedHat** [comment]
@mheon I had: 

```
As problems are encountered along the way, they get added to this page, keeping it a fresh source of information.
```
I've changed it to:

```
As common problems are encountered along the way, the community is encouraged to add them to the troubleshooting page, keeping it a fresh source of information.
```
Let me know if that doesn't address your thought.

**Comment by TomSweeneyRedHat** [comment]
@mheon and @rhatdan I've pushed my latest variant.  I tweaked as shown above in the discussion with @mheon, and a few other small grammatical/reading changes.

**Comment by rhatdan** [comment]
LGTM

**Comment by mheon** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
Two LGTM's, merging.  Thanks all!

**Pull request merged**
