### PR TITLE
post: generate seccomp profiles with podman and ebpf

### PR DESCRIPTION
**Pull request by vrothberg**
Signed-off-by: Valentin Rothberg <rothberg@redhat.com>

### CODE REVIEW

**Comment by vrothberg** [comment]
@TomSweeneyRedHat @rhatdan @weirdwiz PTAL

**Comment by TomSweeneyRedHat** [comment]
LGTM, would love to publish here, but want a head nod from @rhatdan in case he thinks it should be at another site and then linked here.

**Comment by vrothberg** [comment]
> LGTM, would love to publish here, but want a head nod from @rhatdan in case he thinks it should be at another site and then linked here.

The idea is to publish here, and if still possible, write a summary for the Google blog pointing to this article here. It's too big for the Google one which should focus more on the experience working together etc.

**Comment by TomSweeneyRedHat** [comment]
Alrighty then, I'm happy to publish @vrothberg

**Pull request merged**
