### PR TITLE
Add link to Kedar's Container Tech talk

### PR DESCRIPTION
**Pull request by TomSweeneyRedHat**
Add a link to @kedark3 's DevConf.US talk on the container tools.

Signed-off-by: TomSweeneyRedHat <tsweeney@redhat.com>

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
@rhatdan @kedark3 PTAL
@rhatdan, please do NOT merge this until Monday.

**Comment by kedark3** [comment]
Thanks @TomSweeneyRedHat

**Comment by rhatdan** [comment]
LGTM

**Comment by kedark3** [comment]
Thanks @rhatdan @TomSweeneyRedHat  - does this take effect same day to update podman.io or takes some time/manual intervention? just curious.

**Comment by TomSweeneyRedHat** [comment]
@kedark3 once the merge button is pressed, it all gets published automatically and posted on the site.  Usually it takes 5 to 10 minutes to complete, sometimes a bit longer.  I'm a little concerned about this one though, I would have expected it to be up by now....

**Comment by kedark3** [comment]
@TomSweeneyRedHat I've been getting a lot of that lately. Anything I touch becomes a `special case` lol :laughing:

**Pull request merged**
