### PR TITLE
add Discord server info

### PR DESCRIPTION
**Pull request by lsm5**
Signed-off-by: Lokesh Mandvekar <lsm5@fedoraproject.org>

@TomSweeneyRedHat  @rhatdan @infiniteregrets PTAL

### CODE REVIEW

**Comment by lsm5** [comment]
btw, is the slack #crio channel still a good place to suggest for podman questions?

**Comment by mheon** [comment]
I idle in there and answer questions, so yes

**Comment by mheon** [comment]
LGTM

**Comment by infiniteregrets** [comment]
LGTM, thanks!

**Comment by lsm5** [comment]
while we're at it, is there any ask for a dedicated podman slack channel? #crio channel kinda feels like piggybacking :)

**Comment by TomSweeneyRedHat** [comment]
No "official" Podman server on slack, but while experimenting one day with slack, I created one in CoreOS #podman that still lives.  The CRI-O slack channel is under a Kubernetes server, and I don't think we should or could slide under that umbrella at this point.

**Comment by lsm5** [comment]
ya the coreos slack isn't public afaik, so no chance of using that. But if there's enough demand, we could create our own assuming people don't care about the entire chat history https://slack.com/intl/en-ca/pricing . Bridging with matrix is supported as well ;)

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by lsm5** [comment]
hmm, both `podman.slack.com` and `containers.slack.com` are taken. If there's enough interest, I could investigate further. I'm personally happy with just Matrix though :)

**Comment by infiniteregrets** [comment]
Matrix/Discord/IRC are just fine imho

**Comment by TomSweeneyRedHat** [comment]
Ditto @infiniteregrets thoughts

**Comment by lsm5** [comment]
great, i'll forget about it, thanks all :)

**Pull request merged**
