### PR TITLE
Add troubleshooting ptr in Getting Started

### PR DESCRIPTION
**Pull request by TomSweeneyRedHat**
Add a link for the troubleshooting guide to the
Getting Started page in hopes of getting more
exposure for that page.

Signed-off-by: TomSweeneyRedHat <tsweeney@redhat.com>

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
@mheon PTAL

**Comment by TomSweeneyRedHat** [comment]
re-ping @mheon and @rhatdan

**Comment by Luap99** [comment]
I think adding this as menu entry would help even more.

**Comment by TomSweeneyRedHat** [comment]
@Luap99 that's certainly under consideration.  I'm just a little worried about screen space.  I've that and a number of other home page changes that I need to get to.

**Comment by TomSweeneyRedHat** [comment]
ping, @mheon @rhatdan could use some review/merge love here.....

**Comment by mheon** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
@rhatdan PTAL and merge if it LGTY

**Comment by rhatdan** [comment]
LGTM

**Pull request merged**
