### PR TITLE
Update debian and ubuntu commands for podman v3.0.0

### PR DESCRIPTION
**Pull request by lsm5**
Signed-off-by: Lokesh Mandvekar <lsm5@fedoraproject.org>

@TomSweeneyRedHat @rhatdan @vrothberg PTAL

### CODE REVIEW

**Review by TomSweeneyRedHat — COMMENTED** [review]
LGTM
thanks @lsm5

**Comment by lsm5** [comment]
btw, these additions will be necessary mainly because we will be switching to crun instead of runc.

**Review by vrothberg — COMMENTED** [review]
LGTM

**Comment by lsm5** [comment]
thanks, I guess we can wait to merge this until v3.0.0 lands in Kubic Stable project.

**Comment by TomSweeneyRedHat** [comment]
@lsm5 please merge this when it's GTG, or ping me to do so if you don't have the juice to do so.

**Comment by lsm5** [comment]
> @lsm5 please merge this when it's GTG, or ping me to do so if you don't have the juice to do so.

ack, I'll do quick tests on centos as well.

**Pull request merged**
